# Edit this line to force a CI run: 177

# Remove the rules for the triggers, and specify the
# rules inside the child pipelines instead.
# See https://gitlab.com/gitlab-org/gitlab/-/issues/222370

image: registry.gitlab.com/cyber-dojo/ci-runner:v3

stages:
  - trigger

trigger-main:
  stage: trigger
  rules:
    - if: $CI_COMMIT_TAG == null
    - when: never
  trigger:
    include: .gitlab/workflows/main.yml
    strategy: depend

trigger-staging:
  stage: trigger
  rules:
    - if: $CI_COMMIT_TAG == null
    - when: never
  trigger:
    include: .gitlab/workflows/report-to-staging.yml
    strategy: depend
