# See ./gitlab/workflows/readme.md
# See ./gitlab/workflows/dev-readme.md

image: registry.gitlab.com/cyber-dojo/ci-runner:v2.11.23

stages:
  - trigger


trigger-main:
  stage: trigger
  rules:
    - if: $CI_COMMIT_TAG == null
    - when: never
  trigger:
    include: .gitlab/workflows/main.yml
    strategy: depend

