# Edit this line to force a CI run: 168

image: registry.gitlab.com/cyber-dojo/ci-runner:v2

stages:
  - trigger

trigger-main:
  stage: trigger
  trigger:
    include: .gitlab/workflows/main.yml
    strategy: depend

trigger-staging:
  stage: trigger
  trigger:
    include: .gitlab/workflows/report-to-staging.yml
    strategy: depend
