
# This is augmented with dependent services by
# sh/augmented_docker_compose.sh

version: '3.7'

services:

  nginx:
    build:
      context: source/nginx_stub
    container_name: test-creator-nginx
    depends_on:
      - creator-server
    image: cyberdojo/nginx_custom_stub
    init: true
    ports: [ "80:80" ]
    user: root

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  creator-client:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CREATOR_CLIENT_PORT ]
      context: source/client
    container_name: test-creator-client
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - creator-server
    image: cyberdojo/creator-client
    ports: [ "${CYBER_DOJO_CREATOR_CLIENT_PORT}:${CYBER_DOJO_CREATOR_CLIENT_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  creator-server:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CREATOR_PORT ]
      context: source/server
    container_name: test-creator-server
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - saver
      - puller
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_CREATOR_IMAGE}
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]
