
version: '3.7'

services:

  creator-client:
    #build:
    #  context: app/test_client
    depends_on:
      - custom-start-points
      - creator-server
    user: nobody
    image: cyberdojo/creator-client
    init: true
    container_name: test-creator-client
    ports: [ "4522:4522" ]
    read_only: true
    restart: "no"
    volumes: [ ./app/test_client:/app/test:ro ]
    tmpfs: /tmp

  creator-server:
    build:
      context: app
      args: [ SHA, CYBER_DOJO_CREATOR_PORT ]
    depends_on:
      - custom-start-points
      - saver
    user: nobody
    image: ${CYBER_DOJO_CREATOR_IMAGE}
    init: true
    container_name: test-creator-server
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    restart: "no"
    volumes: [ ./app/test_server:/app/test_server:ro ]
    tmpfs: /tmp

  custom-start-points:
    user: nobody
    image: ${CYBER_DOJO_CUSTOM}
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "4526:4526" ]
    restart: "no"
    tmpfs: /tmp

  saver:
    user: saver
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    restart: "no"
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533
    
