
services:

  nginx:
    image: cyberdojo/nginx_creator_stub
    container_name: test_nginx
    ports: [ "${CYBER_DOJO_NGINX_PORT}:${CYBER_DOJO_NGINX_PORT}" ]
    user: root
    build:
      context: nginx_stub
    depends_on:
      - client

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  client:
    build:
      args: [ COMMIT_SHA ]
      context: client
    image: ${CYBER_DOJO_CREATOR_CLIENT_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    container_name: ${CYBER_DOJO_CREATOR_CLIENT_CONTAINER_NAME}
    env_file: [ .env ]
    ports: [ "${CYBER_DOJO_CREATOR_CLIENT_PORT}:${CYBER_DOJO_CREATOR_CLIENT_PORT}" ]
    user: ${CYBER_DOJO_CREATOR_CLIENT_USER}
    depends_on:
      - custom-start-points    # for test data
      - exercises-start-points # for test data
      - languages-start-points # for test data
      - selenium
      - creator
    read_only: true
    restart: "no"
    volumes:
      - "./test:/app/test/:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  creator:
    build:
      args: [ COMMIT_SHA ]
      context: .
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    container_name: ${CYBER_DOJO_CREATOR_SERVER_CONTAINER_NAME}
    env_file: [ .env ]
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    user: ${CYBER_DOJO_CREATOR_SERVER_USER}
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - runner
      - saver
    read_only: true
    restart: "no"
    volumes:
      - "./test:/app/test/:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

  custom-start-points:
    image: ${CYBER_DOJO_CUSTOM_START_POINTS_IMAGE}:${CYBER_DOJO_CUSTOM_START_POINTS_TAG}
    user: nobody
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

  exercises-start-points:
    image: ${CYBER_DOJO_EXERCISES_START_POINTS_IMAGE}:${CYBER_DOJO_EXERCISES_START_POINTS_TAG}
    user: nobody
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

  languages-start-points:
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS_IMAGE}:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG}
    user: nobody
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB


  runner:
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    user: root
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB

  saver:
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    user: saver
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    env_file: [ .env ]
    init: true
    read_only: true
    restart: "no"
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533

  selenium:
    image: selenium/standalone-firefox
    ports: [ "4444:4444" ]
