
# This is augmented with dependent services by
# sh/augmented_docker_compose.sh

version: '3.7'

services:

  nginx:
    image: cyberdojo/nginx_creator_stub
    container_name: test_nginx
    ports: [ "${CYBER_DOJO_NGINX_PORT}:${CYBER_DOJO_NGINX_PORT}" ]
    user: root
    build:
      context: source/nginx_stub

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  client:
    image: ${CYBER_DOJO_CREATOR_CLIENT_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    container_name: ${CYBER_DOJO_CREATOR_CLIENT_CONTAINER_NAME}
    ports: [ "${CYBER_DOJO_CREATOR_CLIENT_PORT}:${CYBER_DOJO_CREATOR_CLIENT_PORT}" ]
    user: ${CYBER_DOJO_CREATOR_CLIENT_USER}
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CREATOR_CLIENT_PORT ]
      context: source/client
    depends_on:
      - nginx
      - custom-start-points    # for test data
      - exercises-start-points # for test data
      - languages-start-points # for test data
      - selenium
      - creator
    env_file:
      - .env
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes: [ "./test:/test/:ro" ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  creator:
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}
    container_name: ${CYBER_DOJO_CREATOR_SERVER_CONTAINER_NAME}
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    user: ${CYBER_DOJO_CREATOR_SERVER_USER}
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CREATOR_PORT ]
      context: source/server
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - runner
      - model
    env_file:
      - .env
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes: [ "./test:/test/:ro" ]
