
version: '3.7'

services:

  creator-client:
    #build:
    #  context: test_client
    depends_on:
      - custom-start-points
      - creator-server
    image: cyberdojo/creator-client
    init: true
    container_name: test-creator-client
    ports: [ "4522:4522" ]
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: "no"

  creator-server:
    build:
      context: .
      args: [ SHA, CYBER_DOJO_CREATOR_PORT ]
    depends_on:
      - saver
    user: nobody
    image: ${CYBER_DOJO_CREATOR_IMAGE}
    init: true
    container_name: test-creator-server
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    restart: "no"
    volumes: [ "./test_server:/app/test:ro" ]
    tmpfs: [ "/tmp:exec,mode=1777" ] # Sticky bit must be set on /tmp otherwise
                                     # Dir.mktmpdir(id,'/tmp') complains
  saver:
    user: saver
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    init: true
    container_name: test-saver
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    restart: 'no'
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533

  custom-start-points:
    user: nobody
    image: ${CYBER_DOJO_CUSTOM}
    init: true
    container_name: test-custom-start-points
    environment: [ NO_PROMETHEUS ]
    read_only: true
    ports: [ "4526:4526" ]
    tmpfs: /tmp
    restart: 'no'
