version: 2

jobs:

  build-test-publish:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Build image, test it, publish it on Dockerhub
          command: |
            # DOCKER_USER, DOCKER_PASS are in the context
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
            ./build_test_publish.sh || true
            docker logout

  deploy-to-beta-env:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to beta with helm
          command: |
            ./.circleci/deploy_to_namespace.sh beta

  log-beta-deployment-to-merkely:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Log deployment to beta in Merkely
          command: |
            ./.circleci/merkely_log_deployment.sh beta

  deploy-to-prod-env:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to prod with helm
          command: |
            ./.circleci/deploy_to_namespace.sh prod

  log-prod-deployment-to-merkely:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Log deployment to prod in Merkely
          command: |
            ./.circleci/merkely_log_deployment.sh prod


workflows:

  version: 2

  build:
    jobs:

      - build-test-publish:
          context: cyberdojo-context
          filters:
            branches:
              only: [ master ]

      - deploy-to-beta-env:
          context: cyberdojo-context
          requires: [ build-test-publish ]

      - log-beta-deployment-to-merkely:
          context: cyberdojo-context
          requires: [ deploy-to-beta-env ]

      - approve-to-prod-env:
          type: approval
          requires: [ log-beta-deployment-to-merkely ]

      - deploy-to-prod-env:
          context: cyberdojo-context
          requires: [ approve-to-prod-env ]

      - log-prod-deployment-to-merkely:
          context: cyberdojo-context
          requires: [ deploy-to-prod-env ]

