
fullnameOverride: "creator"

replicaCount: 1

service:
  port: 4523
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4523"

volumes:
  - name: creator-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: creator
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: creator-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
    livenessProbe:
      path: /alive?
      port: 4523
    readinessProbe:
      path: /ready?
      port: 4523

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
