
image: registry.gitlab.com/cyber-dojo/ci-runner:v2

stages:
  - kosli-start-trail-stage
  - wait-for-image-stage
  - test-stage
  - wait-for-beta-deployment-stage
  - prod-approval-stage
  - sdlc-control-gate-stage
  - wait-for-prod-deployment-stage
  - post-deployment-stage


variables:
  # KOSLI_DRY_RUN: true
  KOSLI_ORG: cyber-dojo
  KOSLI_FLOW: creator
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"


kosli-start-trail:
  stage: kosli-start-trail-stage
  script:
    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit 0 ; fi

    - kosli create flow ${KOSLI_FLOW}
        --description "UX for Group/Kata creation"
        --template artifact,unit-test,branch-coverage,snyk-scan,pull-request  
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}


wait-for-image:
  stage: wait-for-image-stage
  needs: [ kosli-start-trail ]
  services: [ docker:24.0.5-dind ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - IMAGE_NAME=cyberdojo/${CI_PROJECT_NAME}:${CI_COMMIT_SHA:0:7}
    - ./sh/wait_for_image.sh "${IMAGE_NAME}

    - mkdir kosli
    - FINGERPRINT=$(kosli fingerprint ${IMAGE_NAME} --artifact-type=docker)
    - echo ${FINGERPRINT} > kosli/fingerprint
    - echo ${IMAGE_NAME}  > kosli/image_name

    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit 0 ; fi

    - kosli report artifact $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}


unit-test:
  stage: test-stage
  needs: [ wait-for-image ]
  services: [ docker:24.0.5-dind ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - set +e
    - source ./sh/run_tests_with_coverage.sh
    - run_tests_with_coverage
    - STATUS=$?
    - set -e

    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit ${STATUS} ; fi

    - kosli report evidence artifact junit $(cat kosli/image_name)
           --fingerprint=$(cat kosli/fingerprint)
           --name=unit-test
           --results-dir=test/server/reports/junit
           --host=${KOSLI_HOST_STAGING}
           --api-token=${KOSLI_API_TOKEN_STAGING}

    - KOSLI_COMPLIANT=$([ ${STATUS} = 0 ] && echo true || echo false)

    - kosli report evidence artifact generic $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --compliant=${KOSLI_COMPLIANT}
        --description="server & client branch-coverage reports"
        --name=branch-coverage
        --user-data=./test/evidence.json 
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}

    - exit ${STATUS}


security-scan:
  stage: test-stage
  needs: [ wait-for-image ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - set +e
    - snyk container test $(cat kosli/image_name)
        --file=Dockerfile
        --json-file-output=snyk.json
        --policy-path=.snyk
    - STATUS=$?
    - set -e

    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit $STATUS ; fi

    - kosli report evidence artifact snyk $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --name=snyk-scan
        --scan-results=snyk.json
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}

    - exit ${STATUS}


pull-request:
  stage: test-stage
  needs: [ wait-for-image ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit 0 ; fi

    - kosli report evidence artifact pullrequest gitlab $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)           
        --name=pull-request
        --gitlab-token=${KOSLI_GITLAB_TOKEN} 
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}      
        --assert


wait-for-beta-deployment:
  stage: wait-for-beta-deployment-stage
  needs: [ unit-test, security-scan, pull-request ]
  services: [ docker:24.0.5-dind ]
  artifacts:
    paths: [ kosli/ ]
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_BETA}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_BETA}
    KOSLI_ENVIRONMENT_NAME: aws-beta
  script:
    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit 42 ; fi

    - kosli expect deployment $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --description "Deployed to ${KOSLI_ENVIRONMENT_NAME} in Gitlab pipeline"
        --environment ${KOSLI_ENVIRONMENT_NAME} 
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}

    - ./sh/wait_for_deployment.sh 
        $(cat kosli/image_name)
        ${KOSLI_HOST_STAGING}
        ${KOSLI_API_TOKEN_STAGING}
        ${KOSLI_ORG}
        ${KOSLI_ENVIRONMENT_NAME}


prod-approval:
  stage: prod-approval-stage
  needs: [ wait-for-beta-deployment ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit 42 ; fi

    - kosli report approval $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --description="Approved in Gitlab pipeline"
        --environment=aws-prod
        --approver="${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>"
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}


sdlc-control-gate:
  stage: sdlc-control-gate-stage
  needs: [ prod-approval ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - kosli assert artifact $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}


wait-for-prod-deployment:
  stage: wait-for-prod-deployment-stage
  needs: [ sdlc-control-gate ]
  services: [ docker:24.0.5-dind ]
  artifacts:
    paths: [ kosli/ ]
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_PROD}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_PROD}
    KOSLI_ENVIRONMENT_NAME: aws-prod
  script:
    - if [ "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" ] ; then exit 42 ; fi

    - kosli expect deployment $(cat kosli/image_name)
        --fingerprint=$(cat kosli/fingerprint)
        --description "Deployed to ${KOSLI_ENVIRONMENT_NAME} in Gitlab pipeline"
        --environment ${KOSLI_ENVIRONMENT_NAME}
        --host=${KOSLI_HOST_STAGING}
        --api-token=${KOSLI_API_TOKEN_STAGING}

    - ./sh/wait_for_deployment.sh 
        $(cat kosli/image_name)
        ${KOSLI_HOST_STAGING}
        ${KOSLI_API_TOKEN_STAGING}
        ${KOSLI_ORG}
        ${KOSLI_ENVIRONMENT_NAME}


push-latest-image-to-public-registry:
  stage: post-deployment-stage
  needs: [ wait-for-prod-deployment ]
  services: [ docker:24.0.5-dind ]
  artifacts:
    paths: [ kosli/ ]
  script:
    - docker pull $(cat kosli/image_name)
    - docker tag $(cat kosli/image_name) cyberdojo/${CI_PROJECT_NAME}:latest
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - docker push cyberdojo/${CI_PROJECT_NAME}:latest
