image: registry.gitlab.com/cyber-dojo/ci-runner:v8

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /See merge request/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - pre-stage

variables:
  # KOSLI_DRY_RUN: false                   # Org env-var
  # KOSLI_FLOW: creator                    # Repo env-var
  KOSLI_ORG: cyber-dojo
  KOSLI_HOST: ${KOSLI_HOST_PROD}           # Org env-var  https://app.kosli.com
  KOSLI_API_TOKEN: ${KOSLI_API_TOKEN_PROD} # Org env-var
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"


pre:
  stage: pre-stage
  script:
    - git status
