name: Main

on:
  push:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.prep.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo "image_tag=${TAG}" >> ${GITHUB_OUTPUT}

  build-test-push:
    needs: [pre-build]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_build_test_push.yml@v0.0.1
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      BUILD_COMMAND: build_test_publish.sh
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      image_tag: ${{ needs.pre-build.outputs.image_tag }}
      ecr_registry: 244531986313.dkr.ecr.eu-central-1.amazonaws.com
      service_name: creator
      gh_actions_iam_role_name: gh_actions_services

  deploy-staging:
    needs: [pre-build, build-test-push]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_deploy.yml@v0.0.2
    permissions:
      id-token: write
      contents: write
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    with:
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      cyber_dojo_env_name_aws: aws-beta
      environment_name: staging
      environment_url: https://beta.cyber-dojo.org
      gh_actions_iam_role_name: gh_actions_services
      kosli_host_production: https://app.kosli.com
      kosli_host_staging: https://staging.app.kosli.com
      tagged_image: 244531986313.dkr.ecr.eu-central-1.amazonaws.com/creator:${{ needs.pre-build.outputs.image_tag }}

  deploy-prod:
    needs: [pre-build, build-test-push]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_deploy.yml@v0.0.2
    permissions:
      id-token: write
      contents: write
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    with:
      AWS_ACCOUNT_ID: 274425519734
      AWS_REGION: eu-central-1
      cyber_dojo_env_name_aws: aws-prod
      environment_name: production
      environment_url: https://cyber-dojo.org
      gh_actions_iam_role_name: gh_actions_services
      kosli_host_production: https://app.kosli.com
      kosli_host_staging: https://staging.app.kosli.com
      tagged_image: 274425519734.dkr.ecr.eu-central-1.amazonaws.com/creator:${{ needs.pre-build.outputs.image_tag }}