name: Main

on:
  push:
    branches:
      - master

jobs:
  pre-build:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.prep.outputs.tag }}
    steps:

    - uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo "TAG=${TAG}" >> ${GITHUB_ENV}
        echo ::set-output name=tag::${TAG}

  build-test-push:
    needs: [pre-build]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_build_test_push.yml@master
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    with:
      BUILD_COMMAND: build_test_publish.sh
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      tag: ${{ needs.pre-build.outputs.tag }}
      ecr_registry: 244531986313.dkr.ecr.eu-central-1.amazonaws.com
      service_name: creator
      gh_actions_iam_role_name: gh_actions_services

  deploy-staging:
    needs: [pre-build, build-test-push]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_deploy.yml@master
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
    with:
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      cyber_dojo_env_name_aws: aws-beta
      environment_name: staging
      environment_url: https://beta.cyber-dojo.org
      gh_actions_iam_role_name: gh_actions_services
      kosli_host_production: https://app.kosli.com
      kosli_host_staging: https://staging.app.kosli.com
      tagged_image: 244531986313.dkr.ecr.eu-central-1.amazonaws.com/creator:${{ needs.pre-build.outputs.tag }}

  deploy-prod:
    needs: [pre-build, build-test-push]
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_deploy.yml@master
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
    with:
      AWS_ACCOUNT_ID: 274425519734
      AWS_REGION: eu-central-1
      cyber_dojo_env_name_aws: aws-prod
      environment_name: production
      environment_url: https://cyber-dojo.org
      gh_actions_iam_role_name: gh_actions_services
      kosli_host_production: https://app.kosli.com
      kosli_host_staging: https://staging.app.kosli.com
      tagged_image: 274425519734.dkr.ecr.eu-central-1.amazonaws.com/creator:${{ needs.pre-build.outputs.tag }}
